name = "joncorv-site"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[vars]
PNPM_VERSION = "10"

[[d1_databases]]
binding = "DB"
database_name = "joncorv-site-db"
database_id = "e789fad4-e830-4560-bc0d-088055e9edef"
